FinalProiect/FinalProiect/Models/Product.cs
using FinalProiect.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Incercare2Proiect.Models
{
    public class Product
    {
        [Key]
        public int ProductId { get; set; }
        [Required(ErrorMessage = "Numele este obligatoriu")]
        [StringLength(100, ErrorMessage = "Numele nu poate avea mai mult de 20 caractere")]
        public string Nume { get; set; }
        [Required(ErrorMessage = "Pretul este obligatoriu")]
        public int Pret { get; set; }
        [StringLength(1000, ErrorMessage = "Descrierea nu poate avea mai mult de 1000 caractere")]
        public string Descriere { get; set; }
        public string ImageName { get; set; }

        public int Suma { get; set; }
        public double Medie { get; set; }
        public float Numar { get; set; }

        public bool Accept { get; set; }

        public int CategoryId { get; set; }
        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }


        public virtual Category Category { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public IEnumerable<SelectListItem> Categ { get; set; }


        public int? OrderBy { get; set; }
    }
}

FinalProiect/FinalProiect/Controllers/ProductsController.cs
using FinalProiect.Models;
using Incercare2Proiect.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Incercare2Proiect.Controllers
{
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private int _perPage = 6;
        // GET: Products

        public ActionResult Index(int? orderBy)
        {
            // aducem produsele din memeorie in variabila products
            IEnumerable<Product> products = db.Products.Where( a => a.Accept == true).Include("Category").Include("User").OrderBy(async => async.Pret);
            ViewBag.Products = products;
            // sortam produsele in functie de alegerea noastra
            if (orderBy == 1)
            {
                products = db.Products.Include("Category").Include("User").OrderBy(a => a.Pret);
            }
            else if (orderBy == 2)
            {
                products = db.Products.Include("Category").Include("User").OrderByDescending(a => a.Pret);
            }
            else if (orderBy == 3)
            {
                products = db.Products.Include("Category").Include("User").OrderBy(a => a.Nume);
            }
            else if (orderBy == 4) // if (orderBy == 4)
            {
                products = db.Products.Include("Category").Include("User").OrderByDescending(a => a.Nume);
            }
            else 
            {
                products = db.Products.Include("Category").Include("User").OrderByDescending(a => a.Medie);
            }
            //var products = db.Products.Include("Category").Include("User").OrderBy(a => a.Pret);
            var produse = db.Products.Where(a => a.Accept == true).Include("Category").Include("User").OrderBy(a => a.Pret);
            ViewBag.Products = produse;
            var search = "";

            if ( Request.Params.Get("search") != null)
            {
                // alegem produsele care contin ce am introdus in search
                search = Request.Params.Get("search").Trim();
                List<int> productIds = db.Products.Where(
                    at => at.Nume.Contains(search)
                    || at.Descriere.Contains(search)
                    ).Select(a => a.ProductId).ToList();

                List<int> reviewIds = db.Reviews.Where(c => c.Continut.Contains(search))
                    .Select(rev => rev.ProductId).ToList();

                List<int> mergeIds = productIds.Union(reviewIds).ToList();

                // alegem produsele in functie de ce am aleg la sortare
                if (orderBy == 1)
                {
                    products = db.Products.Where(product => mergeIds.Contains(product.ProductId)).Include("Category").Include("User").OrderBy(async => async.Pret);
                }
                else if (orderBy == 2)
                {
                    products = db.Products.Where(product => mergeIds.Contains(product.ProductId)).Include("Category").Include("User").OrderByDescending(async => async.Pret);
                }
                else if (orderBy == 3)
                {
                    products = db.Products.Where(product => mergeIds.Contains(product.ProductId)).Include("Category").Include("User").OrderBy(async => async.Nume);
                }
                else  if (orderBy == 4)
                {
                    products = db.Products.Where(product => mergeIds.Contains(product.ProductId)).Include("Category").Include("User").OrderByDescending(async => async.Nume);
                }

                else 
                {
                    products = db.Products.Where(product => mergeIds.Contains(product.ProductId)).Include("Category").Include("User").OrderByDescending(async => async.Medie);
                }

                //products = db.Products.Where(product => mergeIds.Contains(product.ProductId)).Include("Category").Include("User").OrderBy(async => async.Pret);
            }
            // numaram produsele de afisat
            var totalItems = products.Count();
            var currentPage = Convert.ToInt32(Request.Params.Get("page"));

            var offset = 0;

            if (!currentPage.Equals(0))
            {
                offset = (currentPage - 1) * this._perPage;
            }

            var paginatedProducts = products.Skip(offset).Take(this._perPage).OrderByDescending(async => async.Nume);
            if (orderBy == 1)
            {
                paginatedProducts = products.Skip(offset).Take(this._perPage).OrderBy(async => async.Pret);
            }
            else if (orderBy == 2)
            {
                paginatedProducts = products.Skip(offset).Take(this._perPage).OrderByDescending(async => async.Pret);
            }
            else if (orderBy == 3)
            {
                paginatedProducts = products.Skip(offset).Take(this._perPage).OrderBy(async => async.Nume);
            }
            else
            {
                paginatedProducts = products.Skip(offset).Take(this._perPage).OrderByDescending(async => async.Medie);
            }
            /*
            else //if (orderBy == 4)
            {
                paginatedProducts = products.Skip(offset).Take(this._perPage).OrderByDescending(async => async.Nume);
            }
            */

            // var paginatedProducts = products.Skip(offset).Take(this._perPage);

            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }

            ViewBag.perPage = this._perPage;
            ViewBag.total = totalItems;
            ViewBag.lastPage = Math.Ceiling((float)totalItems / (float)this._perPage);

            ViewBag.Products = paginatedProducts;

            ViewBag.OrderBy = orderBy;

            return View();
        }

        //GET : Products(In asteptare)
        public ActionResult Waiting()
        {
            var products = db.Products.Where(a => a.Accept == false).Include("Category").Include("User").OrderBy(async => async.Pret);
            ViewBag.Products = products;

            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
            }

            return View();
        }

        // GET: Upload
        [Authorize(Roles = "Admin, Colaborator")]
        public ActionResult SaveImages()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Colaborator")]
        public ActionResult SaveImages(HttpPostedFileBase file)
        {

            var path = "";
            if (file != null)
            {
                if (file.ContentLength > 0)
                {
                    if (Path.GetExtension(file.FileName).ToLower() == ".jpg"
                    || Path.GetExtension(file.FileName).ToLower() == ".jpeg"
                    || Path.GetExtension(file.FileName).ToLower() == ".png"
                    || Path.GetExtension(file.FileName).ToLower() == ".gif")
                    {
                        path = Path.Combine(Server.MapPath("~/Content/UploadedImages"), file.FileName);
                        file.SaveAs(path);
                        return RedirectToAction("New");

                    }
                    else
                    {
                        return View();
                    }
                }
                else
                { return View(); }

            }
            else
            {
                return View();
            }


        }

        public ActionResult Show(int id)
        {
            
            Product product = db.Products.Find(id);
            ViewBag.afisareButoane = false;

            if (User.IsInRole("Colaborator") || User.IsInRole("Admin"))
            {
                ViewBag.afisareButoane = true;
            }

            ViewBag.esteAdmin = User.IsInRole("Admin");
            ViewBag.utilizatorCurent = User.Identity.GetUserId();
            /////////
            var rol = false;
            if (User.IsInRole("Admin") || User.IsInRole("Colaborator") || User.IsInRole("User"))
                rol = true;
            ViewBag.rol = rol;
            ViewBag.afisareButoane1 = false;
            if (User.IsInRole("Admin"))
            {
                ViewBag.afisareButoane1 = true;
            }
            ViewBag.utilizatorCurent1 = User.Identity.GetUserId();
            return View(product);
        }

        [HttpPost]
        public ActionResult Show(Review rev)
        {
            
            rev.Date = DateTime.Now;
            rev.UserId = User.Identity.GetUserId();
            Product prod = db.Products.Find(rev.ProductId);
            try
            {
                if (ModelState.IsValid)
                {
                    
                    db.Reviews.Add(rev);
                    prod.Suma = prod.Suma + 1;
                    prod.Numar = prod.Numar + rev.Nota;
                    prod.Medie = prod.Numar / prod.Suma;
                    db.SaveChanges();
                    return Redirect("/Products/Show/" + rev.ProductId);
                }
                
                else
                {
                    Product a = db.Products.Find(rev.ProductId);
                    return View(a);
                }

            }

            catch (Exception e)
            {
                Product a = db.Products.Find(rev.ReviewId);
                return View(a);
            }

        }

        //Adauga
        [Authorize(Roles = "Admin,Colaborator")]
        public ActionResult New()
        {
            Product product = new Product();
            product.Categ = GetAllCategories();
            product.UserId = User.Identity.GetUserId();
            
            return View(product);
                
        }

        [HttpPost]

FinalProiect/FinalProiect/Controllers/ShoppingCartController.cs
using FinalProiect.Models;
using FinalProiect.ViewModels;
using Incercare2Proiect.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalProiect.Controllers
{
    [Authorize(Roles = "Admin, Colaborator, User")]
    public class ShoppingCartController : Controller
    {
        ApplicationDbContext storeDB = new ApplicationDbContext();

        // GET: ShoppingCart
        public ActionResult Index()
        {
           

            var CartId = User.Identity.GetUserName();
            var cart = ShoppingCart.GetCart(CartId);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedProduct = storeDB.Products
                .Single(product => product.ProductId == id);

            // Add it to the shopping cart
            var CartId = User.Identity.GetUserName();
            var cart = ShoppingCart.GetCart(CartId);

            cart.AddToCart(addedProduct);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var CartId = User.Identity.GetUserName();
            var cart = ShoppingCart.GetCart(CartId);

            // Get the name of the album to display confirmation
            string productName = storeDB.Carts
                .Single(item => item.RecordId == id).Product.Nume;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(productName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return RedirectToAction("Index");
        }
      
    }
}

FinalProiect/FinalProiect/Views/Products/Edit.cshtml
@model Incercare2Proiect.Models.Product

@{
    ViewBag.Title = "Edit";
}


<form method="post" action="/Products/Edit/@Model.ProductId">

    @Html.HttpMethodOverride(HttpVerbs.Put)
    <br />
    @Html.HiddenFor(m => m.ProductId)

    @Html.Label("Nume", "Nume produs")
    <br />
    @Html.EditorFor(m => m.Nume)
    @Html.ValidationMessageFor(m => m.Nume, "", new { @class = "text-danger" })
    <br /><br />

    @Html.Label("ImageName", "Nume imagine")
    <br />
    @Html.EditorFor(m => m.ImageName)
    @Html.ValidationMessageFor(m => m.ImageName, "", new { @class = "text-danger" })
    <br /><br />
    @Html.Label("Pret", "Pret produs")
    <br />
    @Html.EditorFor(m => m.Pret)
    @Html.ValidationMessageFor(m => m.Pret, "", new { @class = "text-danger" })
    <br /><br />
    @Html.Label("Descriere", "Descriere produs")
    <br />
    @Html.Editor("Descriere", new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(m => m.Descriere, "", new { @class = "text-danger" })
    <br /><br />
    <label>Selectati categoria</label>
    @Html.DropDownListFor(m => m.CategoryId,
    new SelectList(Model.Categ, "Value", "Text"),
    "Selectati categoria", new { @class = "form-control" })
    <br />
    <button class="btn btn-sm btn-success" type="submit">Modifica produs</button>

</form>

FinalProiect/FinalProiect/Views/Products/Index.cshtml
@{
    /**/

    ViewBag.Title = "Produse";
}

<h2>Produse</h2>

<!-- sagetile -->
<div>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <!-- sageata ce duce la prima pagina -->
            <li>
                <a href="/Products/Index?page=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

            <!-- numarul de pagini -->
            @for (int i = 1; i <= ViewBag.lastPage; i++)
            {
                <li><a href="/Products/Index?page=@(i)&search=@(ViewBag.SearchString)&OrderBy=@(ViewBag.OrderBy)">@(i)</a></li>
            }

            <!-- sageata ce duce la ultima pagina -->
            <li>
                <a href="/Products/Index?page=@(ViewBag.lastPage)&search=@(ViewBag.SearchString)&OrderBy=@(ViewBag.OrderBy)" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

<!-- motorul de cautare -->
<div class="container">
    <br />
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-8">
            <form class="card card-sm" method="GET">
                <div class="card-body row no-gutters align-items-center">
                    <div class="col-auto">
                        <i class="fas fa-search h4 text-body"></i>
                    </div>
                    <!-- bara de cautare -->
                    <!--end of col-->
                    <div class="col">
                        <input class="form-control form-control-lg form-controlborderless pull-left bara" type="text" name="search"
                               value="@ViewBag.SearchString"
                               placeholder="Cautare..">
                        <button class="glyphicon glyphicon-search col-xs-pull-5 " style="font-size: 25px; border:none; background-color:#FFD556;"
                                type="submit"></button>
                    </div>
                    <br /><br />
                    <!-- lupa, butonul de search -->
                    <!--end of col-->
                    <!-- drop down list -->
                    <div>
                        <div class="form-group">

                            @Html.Label("OrderBy", "Sort by")
                            @Html.DropDownList("OrderBy", new List<SelectListItem>

                             {
                                new SelectListItem{ Text="Preț crescator", Value = "1" },
                                new SelectListItem{ Text="Preț descrescator", Value = "2" },
                                new SelectListItem{ Text="A-Z", Value = "3" },
                                new SelectListItem{ Text="Z-A", Value = "4" },
                                new SelectListItem{ Text="Rating", Value = "5" }
                             }, "-- Order By --", new { @class = "form-control" })

                            <input type="submit" class="btn btn-default categ" value="Filter" />
                        </div>
                    </div>
                    <!--end of col-->
                </div>
            </form>
        </div>
        <!--end of col-->
    </div>
</div>

<br />

<!-- afisarea produselor -->
@foreach (var product in ViewBag.Products)
{
    if (product.Accept == true)

    { <div class="col-md-4">
            <div class="card-default" style="width: 32rem; background-color:rgba(128, 128, 128, 0.2); padding:35px; margin-bottom:20px;">
                <img class="card-default-img-top" src="/Content/UploadedImages/@product.ImageName" alt="Card image cap" width="240">
                <div class="card-default-body">
                    <h3 class="card-default-title">@product.Nume</h3>
                    <p class="card-default-text"> <strong>Pret : </strong>@product.Pret</p>
                    <p class="card-default-text">@product.Descriere</p>
                    <p class="card-default-text"> <p class="glyphicon glyphicon-tag"></p> @product.Category.CategoryName</p>
                    <a href="/Products/Show/@product.ProductId" class="btn btn-primary pull-right" style="padding:4px;">Afisare produs</a>
                </div>
            </div>
        </div>

    }

}

FinalProiect/FinalProiect/Views/Products/New.cshtml
@model Incercare2Proiect.Models.Product


<h2>Adaugare produs</h2>
@using (Html.BeginForm(actionName: "New", controllerName: "Products"))
{
    @Html.Label("Nume", "Nume produs")
    <br />
    @Html.TextBox("Nume", null, new { @class = "form-control" })
    @Html.ValidationMessage("Nume", null, new { @class = "text-danger" })
    <br /><br />

    @Html.Label("ImageName", "Nume imagine")
    <br />
    @Html.TextBox("ImageName", null, new { @class = "form-control" })
    @Html.ValidationMessage("ImageName", null, new { @class = "text-danger" })
    <br /><br />

    @Html.Label("Pret", "Pret produs")
    <br />
    @Html.TextBox("Pret", null, new { @class = "form-control" })
    @Html.ValidationMessage("Pret", null, new { @class = "text-danger" })
    <br /><br />

    @Html.Label("Descriere", "Descriere produs")
    <br />
    @Html.TextArea("Descriere", null, new { @class = "form-control" })
    @Html.ValidationMessage("Descriere", null, new { @class = "text-danger" })
    <br /><br />

    <label>Selectati categoria</label>
    @Html.DropDownListFor(m => m.CategoryId, new SelectList(Model.Categ, "Value", "Text"),
        "Selectati categoria", new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.CategoryId, "", new { @class = "text-danger" })
    <br />

    <button class="btn btn-sm btn-success" type="submit">Adauga produs</button>

}

FinalProiect/FinalProiect/Views/Products/SaveImages.cshtml
@using (Html.BeginForm("SaveImages", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h3>Incarcati o imagine pentru noul produs</h3>
    <input  type="file" name="file" value="Browse" />
    <br />
    <input class="sterge" type="submit" value="Upload" />

}

FinalProiect/FinalProiect/Views/Products/Show.cshtml
@model Incercare2Proiect.Models.Product
@{
    ViewBag.Title = Model.Nume;
}
<br />
<a class="btn btn-default" href="/Products/Index">Inapoi la produse</a>
<br />

<br />
<div class="panel panel-default" style="background-color:#fdcb6e; text-align:center;">
    <div class="panel-heading">@Model.Nume</div>
    <img class="card-img-top" src="/Content/UploadedImages/@Model.ImageName" alt="Card image cap" width="240" height="300">
    <div class="panel-body">
        Pret: <strong>@Model.Pret</strong>
        <br /><br />
        <span class="label label-success">@Model.Descriere</span>
        <br /><br />
        <strong> Rating produs : @Model.Medie / 5</strong> <p class="glyphicon glyphicon-star-empty"></p>
        <br/> <br/>
        <i class="glyphicon glyphicon-tag"></i> @Model.Category.CategoryName
        <br />
        <hr>

        @foreach (var rev in Model.Reviews)
        {


        }
        @if (ViewBag.afisareButoane == true && Model.UserId == ViewBag.utilizatorCurent || ViewBag.esteAdmin)
        {

            <a class="btn btn-primary pull-left" href="/Products/Edit/@Model.ProductId">Modifica produs</a>
            <form method="post" action="/Products/Delete/@Model.ProductId">
                @Html.HttpMethodOverride(HttpVerbs.Delete)
                <button class="btn btn-danger pull-right" type="submit">Sterge produs</button>
            </form>

            <div class="clearfix"></div>
        }
        <br />
        <div class="btn btn-success">
            <p class="button glyphicon glyphicon-shopping-cart">
                @Html.ActionLink("Adaugă în coș", "AddToCart", "ShoppingCart", new { id = Model.ProductId }, "")
            </p>
        </div>

    </div>
</div>



<br />
@foreach (var rev in Model.Reviews)
{
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div>
                    <p>@rev.Continut</p>
                    <p> <p class="glyphicon glyphicon-star-empty"></p> @rev.Nota / 5 </p>
                    <small class="pull-right">@rev.Date</small>
                    <i class="glyphicon glyphicon-user"></i> <i>scris de</i> <strong> @rev.User.UserName </strong>

                </div>
                @if (rev.UserId == ViewBag.utilizatorCurent || ViewBag.esteAdmin)
                {
                    <div style="display: inline-block; float : left; margin-right: 15px">
                        <a class="glyphicon glyphicon-pencil" href="/Reviews/Edit/@rev.ReviewId"></a>
                    </div>
                    <div style="display: inline-block; float : left">
                        <form method="post" action="/Reviews/Delete/@rev.ReviewId">
                            @Html.HttpMethodOverride(HttpVerbs.Delete)
                            <button class="glyphicon glyphicon-trash" style="border: none; background: transparent" type="submit"></button>
                        </form>
                    </div>
                }
            </div>

        </div>
        <div class="col-md-2"></div>
    </div>
    <hr />
}

@if (ViewBag.rol == true)
{
    <div class="container" >
        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-8">
                <div class="panel">
                    <form method="post" action="/Products/Show/@Model.ProductId">
                        <div class="panel-body" style="background-color:#fdcb6e;">
                            <input type="hidden" name="ProductId" value="@Model.ProductId" />
                            <label>Continut review</label>
                            <br />
                            <div class="pull-right">
                                <select class="form-control" id="Nota" name="Nota">
                                    <option>Selectare nota </option>
                                    <option>1</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                </select>
                            </div>
                            <textarea class="form-control" name="Continut"></textarea>
                            <br />
                            <button class="btn btn-success " type="submit">Adauga review</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
}

FinalProiect/FinalProiect/Views/Products/Waiting.cshtml
@{
                /**/

                ViewBag.Title = "Waiting";
}

<h2>Produse in curs de analizare</h2>

@foreach (var product in ViewBag.Products)
{
    if (product.Accept == false)
    {<div class="card-default" style="width: 32rem; background-color:rgba(128, 128, 128, 0.2); padding:35px; margin-bottom:20px;">
    <img class="card-img-top" src="/Content/UploadedImages/@product.ImageName" alt="Card image cap" width="240" height="300">
    <div class="card-default-body">
        <h2 class="card-default-title">@product.Nume</h2>
        <p class="card-default-title"><strong>Pret : </strong>@product.Pret</p>
        <p class="card-default-title">@product.Descriere</p>
        <p class="card-default-title"><p class="glyphicon glyphicon-tag"></p>  @product.Category.CategoryName</p>

        <form method="post" action="/Products/Acceptare/@product.ProductId">
            @Html.HttpMethodOverride(HttpVerbs.Put)
            <button class="categ pull-left" type="submit" style="padding:5px;">Acceptare</button>
        </form>
        <form method="post" action="/Products/Delete/@product.ProductId">
            @Html.HttpMethodOverride(HttpVerbs.Delete)
            <button class="stergeCateg pull-right" type="submit" style="padding:5px;">Sterge</button>
        </form>
    </div>
    </div>
    <br />
    <hr />
    <br />
    }


    }

    <br />